CREATE DATABASE IF NOT EXISTS endo_diet CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE endo_diet;

CREATE TABLE users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  token VARCHAR(255),
  token_expire_at DATETIME,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE analysis (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  analyzed_results MEDIUMTEXT NOT NULL,
  image_url VARCHAR(1024) NOT NULL,
  user_id INT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL,
  CONSTRAINT fk_analysis_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);